# Generated by Django 5.1.6 on 2025-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('pool_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('pool_name', models.CharField(default='Крутой бассейн', max_length=100)),
                ('pool_desc', models.CharField(default='0 ряд, 0 секция', max_length=255)),
                ('url', models.URLField(null=True)),
                ('temperature_sensor_id', models.IntegerField(null=True)),
                ('oxygen_saturation_sensor_id', models.IntegerField(null=True)),
                ('pH_sensor_id', models.IntegerField(null=True)),
                ('orp_sensor_id', models.IntegerField(null=True)),
                ('salinity_sensor_id', models.IntegerField(null=True)),
                ('water_level_sensor_id', models.IntegerField(null=True)),
                ('turbidity_sensor_id', models.IntegerField(null=True)),
                ('ammonia_content_sensor_id', models.IntegerField(null=True)),
                ('nitrite_content_sensor_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoolOptimalValues',
            fields=[
                ('pool_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('min_temperature', models.FloatField(default=22.0, null=True)),
                ('max_temperature', models.FloatField(default=24.0, null=True)),
                ('min_oxygen_saturation', models.FloatField(default=7.5, null=True)),
                ('max_oxygen_saturation', models.FloatField(default=9.0, null=True)),
                ('min_pH', models.FloatField(default=6.5, null=True)),
                ('max_pH', models.FloatField(default=8.0, null=True)),
                ('min_orp', models.FloatField(default=100.0, null=True)),
                ('max_orp', models.FloatField(default=250.0, null=True)),
                ('min_salinity', models.FloatField(default=10.0, null=True)),
                ('max_salinity', models.FloatField(default=12.0, null=True)),
                ('min_water_level', models.FloatField(default=50.0, null=True)),
                ('max_water_level', models.FloatField(default=70.0, null=True)),
                ('min_turbidity', models.FloatField(default=5.0, null=True)),
                ('max_turbidity', models.FloatField(default=10.0, null=True)),
                ('min_ammonia_content', models.FloatField(default=0.0, null=True)),
                ('max_ammonia_content', models.FloatField(default=0.07, null=True)),
                ('min_nitrite_content', models.FloatField(default=0.0, null=True)),
                ('max_nitrite_content', models.FloatField(default=0.1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoolStatistic',
            fields=[
                ('pool_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(null=True)),
                ('oxygen_saturation', models.FloatField(null=True)),
                ('pH', models.FloatField(null=True)),
                ('orp', models.FloatField(null=True)),
                ('salinity', models.FloatField(null=True)),
                ('water_level', models.FloatField(null=True)),
                ('turbidity', models.FloatField(null=True)),
                ('ammonia_content', models.FloatField(null=True)),
                ('nitrite_content', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticArduino',
            fields=[
                ('pool_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(null=True)),
                ('oxygen_saturation', models.FloatField(null=True)),
                ('pH', models.FloatField(null=True)),
                ('orp', models.FloatField(null=True)),
                ('salinity', models.FloatField(null=True)),
                ('water_level', models.FloatField(null=True)),
                ('turbidity', models.FloatField(null=True)),
                ('ammonia_content', models.FloatField(null=True)),
                ('nitrite_content', models.FloatField(null=True)),
            ],
        ),
    ]
