# Generated by Django 5.1.6 on 2025-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('AERATOR', 'Аэратор'), ('FEEDER', 'Кормушка'), ('HEATER', 'Нагреватель')], default='AERATOR', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
