# Generated by Django 5.1.6 on 2025-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
