# Generated by Django 5.1.6 on 2025-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_statisticarduino'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticArduino',
            fields=[
                ('pool_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(null=True)),
                ('oxygen_saturation', models.FloatField(null=True)),
                ('pH', models.FloatField(null=True)),
                ('orp', models.FloatField(null=True)),
                ('salinity', models.FloatField(null=True)),
                ('water_level', models.FloatField(null=True)),
                ('turbidity', models.FloatField(null=True)),
                ('ammonia_content', models.FloatField(null=True)),
                ('nitrite_content', models.FloatField(null=True)),
            ],
        ),
    ]
