# Generated by Django 5.1.6 on 2025-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_statisticarduino'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlThingsArduino',
            fields=[
                ('pool_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('freezer', models.BooleanField()),
                ('feeder', models.BooleanField()),
            ],
        ),
    ]
