# Generated by Django 5.1.6 on 2025-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_poolstatistic_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolStream',
            fields=[
                ('pool_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('stream_name', models.CharField(max_length=50, null=True)),
                ('rtsp_url', models.TextField(null=True)),
                ('transcode_pid', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pool',
            name='hls_url',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='rtsp_url',
        ),
    ]
