# Generated by Django 5.1.6 on 2025-03-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_controlthingsarduino'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='hls_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlthingsarduino',
            name='feeder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controlthingsarduino',
            name='freezer',
            field=models.BooleanField(default=False),
        ),
    ]
