# Generated by Django 5.1.6 on 2025-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pooloptimalvalues_ammonia_content_sensor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_ammonia_content',
            field=models.FloatField(default=0.07, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_nitrite_content',
            field=models.FloatField(default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_orp',
            field=models.FloatField(default=250.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_oxygen_saturation',
            field=models.FloatField(default=9.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_pH',
            field=models.FloatField(default=8.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_salinity',
            field=models.FloatField(default=12.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_temperature',
            field=models.FloatField(default=24.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_turbidity',
            field=models.FloatField(default=10.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='max_water_level',
            field=models.FloatField(default=70.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_ammonia_content',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_nitrite_content',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_orp',
            field=models.FloatField(default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_oxygen_saturation',
            field=models.FloatField(default=7.5, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_pH',
            field=models.FloatField(default=6.5, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_salinity',
            field=models.FloatField(default=10.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_temperature',
            field=models.FloatField(default=22.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_turbidity',
            field=models.FloatField(default=5.0, null=True),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='min_water_level',
            field=models.FloatField(default=50.0, null=True),
        ),
    ]
