# Generated by Django 5.1.6 on 2025-04-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_poolstream_remove_pool_hls_url_remove_pool_rtsp_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlThingsArduino',
        ),
    ]
