# Generated by Django 5.1.6 on 2025-03-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pooloptimalvalues_max_ammonia_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooloptimalvalues',
            name='id',
        ),
        migrations.RemoveField(
            model_name='poolstatistic',
            name='id',
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='pool_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poolstatistic',
            name='pool_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
