# Generated by Django 5.1.6 on 2025-03-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pool_hls_url_alter_controlthingsarduino_feeder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='url',
            new_name='rtsp_url',
        ),
    ]
