# Generated by Django 5.1.6 on 2025-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_controlthingsarduino'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='state_percents',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='state_zone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
