# Generated by Django 5.1.6 on 2025-04-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_state_percents_pool_health_percents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
