# Generated by Django 5.1.6 on 2025-04-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_pool_health_percents_alter_pool_health_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooloptimalvalues',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
