# Generated by Django 5.1.6 on 2025-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pooloptimalvalues_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='health_zone',
            field=models.CharField(default='danger', max_length=10, null=True),
        ),
    ]
